### PR TITLE
Delete redundant discussion of circuit breakers

### PR DESCRIPTION
**Pull request by martinduke**

### CODE REVIEW

**Comment by martinduke** [comment]
Is this not covered by S6.1.1?

**Comment by gorryfair** [comment]
No - sorry there are two places where circuit breakers come into play - and two different sets of actors/mechanism. This is not the same. For better or worse the two RFCs ended up with similar names and consecutive RFC numbers, because both can provide a way to prevent significant overload.

1) In the multimedia work there is the notion of a CB to set the transport envelope. This is done in the CC or the framework, and works end-to-end. This is one RFC.

2) Within the network, a device or control plane function can detect the presence of overload, and provide a reaction. This could be for a tunnel, or it could be using counters/measurements in a router or management system. This sheds excess load, either by filtering flows or dropping packets. This is another RFC.

**Review by gorryfair — CHANGES_REQUESTED** [review]
I don't think this is the same thing as {{circuit-breakers}}. This is the endpoint version.

**Comment by martinduke** [comment]
OK, I'll throw this PR away.

**Pull request closed without merging**
