### PR TITLE
Datacenter

### LINKED ISSUE #98: Data centers with really small RTTs should be discussed as a special case
From IETF 119: Data centers with really small RTTs should be discussed as a special case

### PR DESCRIPTION
**Pull request by martinduke**
Fixes #98

### CODE REVIEW

**Comment by gorryfair** [comment]
I think this is the tip of a larger iceberg, and I'd suggest we'd need to go deeper, if the IETF now thinks they may produce specs in this space.

As I recall (others may add to the list), there  are challenges to be considered by a proponent/IETF, which include:
- 1. Does the proposal rely on technologies specified by other Forums/SDOs?
- 2. Does the IETF have sufficient experience of the DC requirements and to review the proposals?
- 3. Does the proposal include experience of interoperability between different implementations? or a plan for this?
- 4. Does the DC traffic share resources with Internet traffic?
- 5. Specifically: does the method to be used *between* DCs or only *within* DCs? - How is this usage scoped? And what happens when the protocol is bridged across an Internet path?

One or more of these has in the past thwarted progress towards adoption in the IETF, can we say something about this?

**Comment by martinduke** [comment]
Do you want to take a shot at it? Do we need a completely different section about DC algorithms?

**Review by gorryfair — APPROVED** [review]
Approving this text - LGTM, I propose to move the additional context on data centres to a separate issue, and resolve in a small separate PR against Section 2 & 3.

**Comment by martinduke** [comment]
OK, it might be good to keep some version of this as a guidance for evaluating general-purpose protocols in datacenters, AND have a totally different section for DC-specific algorithms.

**Pull request merged**
