### PR TITLE
Propose a bufferbloat item in the requirements.

### PR DESCRIPTION
**Pull request by huitema**
Addresses issue #8

### CODE REVIEW

**Review by gorryfair — COMMENTED** [review]
Some comments on Bufferbloat

**Comment by huitema** [comment]
@gorryfair You wrote _"Some comments on Bufferbloat"_ and I am pretty sure these are interesting comments, but I cannot see any. I am afraid something went wrong and they were not published.

**Review by gorryfair — APPROVED** [review]
This looks like reasonable first text pin this topic, thanks Christian (my previous comments appear already to be resolved - so happy to approve this)

**Comment by martinduke** [comment]
A good improvement. I wonder if framing it like "use the full bandwidth and nothing more" would be a more holistic approach that covers a few different requirements at once, but I have no actual text to propose.

**Review by martinduke — APPROVED** [review]

**Pull request merged**
