### PR TITLE
Update Abstract

### PR DESCRIPTION
**Pull request by martinduke**
eliminate some awkward/unnecessary phrases. Include brief rationale for a bis.

### CODE REVIEW

**Review by gorryfair — CHANGES_REQUESTED** [review]
/dealing with/ seems imperfect; is /evaluating/ better?

**Comment by martinduke** [comment]
done

**Review by gorryfair — COMMENTED** [review]
Reading more is this CC /scheme/ or CC /algorithm/ ... to be consistent. I'm not keen on scheme, and would prefer /method/ if we don't like algorithm

**Comment by martinduke** [comment]
OK, how about now?

**Review by gorryfair — APPROVED** [review]

**Pull request merged**
